
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCSharpCompiler.cmake:23 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CSharp compiler identification source file "CMakeCSharpCompilerId.cs" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 5/2/2023 9:08:37 PM.
      Project "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\CompilerIdCSharp.csproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "obj\\x64\\Debug\\".
      CoreCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /define:Platformx64;PlatformToolsetv142 /highentropyva- /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\mscorlib.dll" /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Core.dll" /debug+ /out:obj\\x64\\Debug\\CompilerIdCSharp.exe /target:exe /utf8output /langversion:7.3 CMakeCSharpCompilerId.cs "obj\\x64\\Debug\\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
        CompilerServer: server - server processed compilation - 719aa543-46c8-423a-a8ad-c962f20eb1b4
      CopyFilesToOutputDirectory:
        Copying file from "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\obj\\x64\\Debug\\CompilerIdCSharp.exe" to "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\CompilerIdCSharp.exe".
        CompilerIdCSharp -> W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\CompilerIdCSharp.exe
        Copying file from "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\obj\\x64\\Debug\\CompilerIdCSharp.pdb" to "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\CompilerIdCSharp.pdb".
      PostBuildEvent:
        if not "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn"=="" if exist "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe" set _CSC=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn
        if exist "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\csc.exe" set _CSC=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin
        if "%_CSC%"=="" exit -1
        @echo CMAKE_CSharp_COMPILER=%_CSC%\\csc.exe
        CMAKE_CSharp_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe
      Done Building Project "W:\\Firmware\\CMakeFiles\\3.26.3\\CompilerIdCSharp\\CompilerIdCSharp.csproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.60
      
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.csproj"
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.exe"
      
      Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.pdb"
      
      The CSharp compiler identification could not be found in:
        W:/Firmware/CMakeFiles/3.26.3/CompilerIdCSharp/CompilerIdCSharp.csproj
      
      The CSharp compiler identification is Microsoft Visual Studio, found in:
        W:/Firmware/CMakeFiles/3.26.3/CompilerIdCSharp/CompilerIdCSharp.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCSharpCompiler.cmake:34 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/Roslyn/csc.exe"
    directories:
      source: "W:/Firmware/CMakeFiles/CMakeScratch/TryCompile-3kqa3c"
      binary: "W:/Firmware/CMakeFiles/CMakeScratch/TryCompile-3kqa3c"
    cmakeVariables:
      CMAKE_CSharp_FLAGS: "/platform:x64 /define:TRACE"
      CMAKE_CSharp_FLAGS_DEBUG: "/debug:full /optimize- /warn:3 /errorreport:prompt /define:DEBUG"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CSharp_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: W:/Firmware/CMakeFiles/CMakeScratch/TryCompile-3kqa3c
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_d64ec.csproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n && Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 5/2/2023 9:08:39 PM.
        Project "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\cmTC_d64ec.csproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\Debug\\".
          Creating directory "obj\\x64\\Debug\\".
        CoreCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:3 /define:TRACE;DEBUG /highentropyva- /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\mscorlib.dll" /reference:"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Core.dll" /debug+ /debug:full /optimize- /out:obj\\x64\\Debug\\cmTC_d64ec.exe /target:exe /utf8output /langversion:7.3 W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\testCSharpCompiler.cs "obj\\x64\\Debug\\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
          CompilerServer: server - server processed compilation - ffc045e0-97ab-4166-9e33-e9d90eb7c21a
        CopyFilesToOutputDirectory:
          Copying file from "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\obj\\x64\\Debug\\cmTC_d64ec.exe" to "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\Debug\\cmTC_d64ec.exe".
          cmTC_d64ec -> W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\Debug\\cmTC_d64ec.exe
          Copying file from "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\obj\\x64\\Debug\\cmTC_d64ec.pdb" to "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\Debug\\cmTC_d64ec.pdb".
        Done Building Project "W:\\Firmware\\CMakeFiles\\CMakeScratch\\TryCompile-3kqa3c\\cmTC_d64ec.csproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.51
        
      exitCode: 0
...
